/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SigninIndexImport } from './routes/signin/index'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as ContactIndexImport } from './routes/contact/index'
import { Route as DashboardCreateIndexImport } from './routes/dashboard/create/index'
import { Route as DashboardTripsTripIdIndexImport } from './routes/dashboard/trips/$tripId/index'
import { Route as DashboardTripsTripIdHightlightsCreateImport } from './routes/dashboard/trips/$tripId/hightlights.create'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SigninIndexRoute = SigninIndexImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const ContactIndexRoute = ContactIndexImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardCreateIndexRoute = DashboardCreateIndexImport.update({
  id: '/dashboard/create/',
  path: '/dashboard/create/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardTripsTripIdIndexRoute = DashboardTripsTripIdIndexImport.update({
  id: '/dashboard/trips/$tripId/',
  path: '/dashboard/trips/$tripId/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardTripsTripIdHightlightsCreateRoute =
  DashboardTripsTripIdHightlightsCreateImport.update({
    id: '/dashboard/trips/$tripId/hightlights/create',
    path: '/dashboard/trips/$tripId/hightlights/create',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/create/': {
      id: '/dashboard/create/'
      path: '/dashboard/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof DashboardCreateIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/trips/$tripId/': {
      id: '/dashboard/trips/$tripId/'
      path: '/dashboard/trips/$tripId'
      fullPath: '/dashboard/trips/$tripId'
      preLoaderRoute: typeof DashboardTripsTripIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/trips/$tripId/hightlights/create': {
      id: '/dashboard/trips/$tripId/hightlights/create'
      path: '/dashboard/trips/$tripId/hightlights/create'
      fullPath: '/dashboard/trips/$tripId/hightlights/create'
      preLoaderRoute: typeof DashboardTripsTripIdHightlightsCreateImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/signin': typeof SigninIndexRoute
  '/dashboard/create': typeof DashboardCreateIndexRoute
  '/dashboard/trips/$tripId': typeof DashboardTripsTripIdIndexRoute
  '/dashboard/trips/$tripId/hightlights/create': typeof DashboardTripsTripIdHightlightsCreateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/signin': typeof SigninIndexRoute
  '/dashboard/create': typeof DashboardCreateIndexRoute
  '/dashboard/trips/$tripId': typeof DashboardTripsTripIdIndexRoute
  '/dashboard/trips/$tripId/hightlights/create': typeof DashboardTripsTripIdHightlightsCreateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/contact/': typeof ContactIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/dashboard/create/': typeof DashboardCreateIndexRoute
  '/dashboard/trips/$tripId/': typeof DashboardTripsTripIdIndexRoute
  '/dashboard/trips/$tripId/hightlights/create': typeof DashboardTripsTripIdHightlightsCreateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/settings'
    | '/signin'
    | '/dashboard/create'
    | '/dashboard/trips/$tripId'
    | '/dashboard/trips/$tripId/hightlights/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/settings'
    | '/signin'
    | '/dashboard/create'
    | '/dashboard/trips/$tripId'
    | '/dashboard/trips/$tripId/hightlights/create'
  id:
    | '__root__'
    | '/'
    | '/contact/'
    | '/dashboard/'
    | '/settings/'
    | '/signin/'
    | '/dashboard/create/'
    | '/dashboard/trips/$tripId/'
    | '/dashboard/trips/$tripId/hightlights/create'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SigninIndexRoute: typeof SigninIndexRoute
  DashboardCreateIndexRoute: typeof DashboardCreateIndexRoute
  DashboardTripsTripIdIndexRoute: typeof DashboardTripsTripIdIndexRoute
  DashboardTripsTripIdHightlightsCreateRoute: typeof DashboardTripsTripIdHightlightsCreateRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SigninIndexRoute: SigninIndexRoute,
  DashboardCreateIndexRoute: DashboardCreateIndexRoute,
  DashboardTripsTripIdIndexRoute: DashboardTripsTripIdIndexRoute,
  DashboardTripsTripIdHightlightsCreateRoute:
    DashboardTripsTripIdHightlightsCreateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contact/",
        "/dashboard/",
        "/settings/",
        "/signin/",
        "/dashboard/create/",
        "/dashboard/trips/$tripId/",
        "/dashboard/trips/$tripId/hightlights/create"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/contact/": {
      "filePath": "contact/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx"
    },
    "/signin/": {
      "filePath": "signin/index.tsx"
    },
    "/dashboard/create/": {
      "filePath": "dashboard/create/index.tsx"
    },
    "/dashboard/trips/$tripId/": {
      "filePath": "dashboard/trips/$tripId/index.tsx"
    },
    "/dashboard/trips/$tripId/hightlights/create": {
      "filePath": "dashboard/trips/$tripId/hightlights.create.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
