name: Build and deploy to GCP
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            IMAGE_URL: ${{ secrets.GCP_REGION}}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID}}/wander-wise:${{ github.sha }}
        steps:
            - uses: actions/checkout@v3
            - id: "auth"
              name: Authenticate GCP
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: "${{ secrets.GCLOUD_SERVICE_KEY }}"
            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v1
            - name: Use gcloud CLI
              run: gcloud info
            - name: Configure docker
              run: gcloud auth configure-docker europe-north1-docker.pkg.dev
            - name: Docker Build
              run: >
                  docker build --no-cache -t ${{ env.IMAGE_URL }} 
                  ./backend -f ./backend/Dockerfile 
                  --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} 
                  --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }}
                  --build-arg DB_URL=${{ secrets.DB_URL }}
            - name: Docker Push
              run: docker push $IMAGE_URL
            - name: Update Cloud Run service
              uses: google-github-actions/deploy-cloudrun@v1
              with:
                  env_vars: |-
                      DB_URL=${{secrets.DB_URL}}
                      DB_USERNAME=${{secrets.DB_USERNAME}}
                      DB_PASSWORD=${{secrets.DB_PASSWORD}}
                  region: ${{ secrets.GCP_REGION}}
                  service: WanderWiseBackend
                  image: ${{ env.IMAGE_URL }}
